name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 10.0.x
    - name: Build
      working-directory: TestProject1
      run: dotnet build
    - name: Ensure browsers are installed
      working-directory: TestProject1
      run: pwsh ./bin/Debug/net10.0/playwright.ps1 install --with-deps
    - name: Run your tests
      working-directory: TestProject1
      run: dotnet test