name: Playwright Tests - From Container
on:
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Tests - From Container'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --user root
    steps:
      - uses: actions/checkout@v5

      - name: Install Playwright dependencies
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          apt-get update && apt-get install -y wget
          
      - name: Build
        run: dotnet build
        working-directory: TestProject1

      - name: Install browsers
        run: pwsh ./bin/Debug/net10.0/playwright.ps1 install --with-deps
        working-directory: TestProject1

      - name: Run your tests
        run: dotnet test
        working-directory: TestProject1