name: Playwright Tests - From Container
on:
  workflow_dispatch:
  
jobs:
  playwright:
    name: 'Playwright Tests - From Container'
    runs-on: ubuntu-latest
    container:
      # image: mcr.microsoft.com/playwright/dotnet:v1.51.0-noble
      image: mcr.microsoft.com/playwright/dotnet:v1.59.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v5 
      - name: Build
        run: dotnet build
        working-directory: TestProject1
      - name: Run your tests
        run: dotnet test
        working-directory: TestProject1